/** @format */

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { HeroUIProvider } from "@heroui/system";
import Header from "@/shared/components/Header/Header";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${poppins.className}`}>
        <HeroUIProvider>
          <Header />
          {children}
        </HeroUIProvider>
      </body>
    </html>
  );
}
